#!/usr/bin/env bash

URL_REGEX="(((http|https)://|www\\.)[a-zA-Z0-9.]*[:]?[a-zA-Z0-9./@$&%?$\#=_~-]*)|((magnet:\\?xt=urn:btih:)[a-zA-Z0-9]*)"

# First remove linebreaks and mutt sidebars:
URLS="$(sed 's/.*│//g' | tr -d '\n' | grep -aEo "$URL_REGEX" | uniq | sed 's/^www./http:\/\/www\./g')"
# Since this is unsorted, uniq will only remove adjacent duplicates

# Don't bother proceeding if there are no valid URLs:
if [ -n "$URLS" ]; then
    CHOSEN_URLS="$(echo "$URLS" | dmenu -i -p 'Follow which url?' -l 10)"
    setsid xdg-open "$CHOSEN_URLS" >/dev/null 2>&1 &
fi
